# Projeto Análise de Dados dos Homônimos

Tarefas:
- Importar Resultado Final da Competência
- Importar base de dados do MS (Rejeitadas e Aprovadas)
- Cruzamento e análises

"""
Load content of a DBF file into a Pandas data frame.

The iter() is required because Pandas doesn't detect that the DBF
object is iterable.
"""
from dbfread import DBF
from pandas import DataFrame

dbf = DBF('files/people.dbf')
frame = DataFrame(iter(dbf))

In [3]:
# Importar bibliotecas
import pandas as pd
from dbfread import DBF
from pandas import DataFrame

# Identificação e carregamento dos arquivos
caminho = str(input('Qual a pasta com os arquivos? ')) + '/'
# final = pd.read_excel(caminho + str(input("Nome da planilha de Homônimos analisados: ")) + '.xlsx', index_col=0)
final = pd.read_excel(caminho + 'Resultado Final Homônimos - Comp 06_23 - Proc 07_23' + '.xlsx', index_col=0)
dbfr = DBF(caminho + 'RJSC2307.dbf')
rejeitadas = DataFrame(iter(dbfr))
dbfa = DBF(caminho + 'RDSC2307.dbf')
aprovadas = DataFrame(iter(dbfa))
dbfm = DBF(caminho + 'ERSC2307.dbf')
motivos = DataFrame(iter(dbfm))

print('Planilhas carregadas!')

Qual a pasta com os arquivos? jul-23
Resultado carregado!
Rejeitadas carregada!
Aprovadas carregada!
Motivos carregada!
Planilhas carregadas!

In [6]:
aprovadas

,UF_ZI,ANO_CMPT,MES_CMPT,ESPEC,CGC_HOSP,N_AIH,IDENT,CEP,MUNIC_RES,NASC,...,DIAGSEC9,TPDISEC1,TPDISEC2,TPDISEC3,TPDISEC4,TPDISEC5,TPDISEC6,TPDISEC7,TPDISEC8,TPDISEC9
0,420000,2023,07,01,86245982000105,4223500088280,1,89920000,420640,19900522,...,,0,0,0,0,0,0,0,0,0
1,420000,2023,07,01,86245982000105,4223500088291,1,89950000,420500,19630213,...,,0,0,0,0,0,0,0,0,0
2,420000,2023,07,01,86245982000105,4223500088302,1,89909000,420209,19781116,...,,0,0,0,0,0,0,0,0,0
3,420000,2023,07,01,86245982000105,4223500088313,1,89909000,420209,19830617,...,,0,0,0,0,0,0,0,0,0
4,420000,2023,07,01,86245982000105,4223500088324,1,89950000,420500,19670424,...,,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48715,421935,2023,07,03,95952321000100,4223104591805,1,89148000,421935,19470730,...,,0,0,0,0,0,0,0,0,0
48716,421935,2023,07,03,95952321000100,4223104576372,1,89148000,421935,20020609,...,,0,0,0,0,0,0,0,0,0
48717,421935,2023,07,03,95952321000100,4223104577912,1,89148000,421935,19540325,...,,0,0,0,0,0,0,0,0,0
48718,421935,2023,07,03,95952321000100,4223104580244,1,89157000,421940,20060617,...,,0,0,0,0,0,0,0,0,0
48719,421935,2023,07,03,95952321000100,4223104575866,1,89148000,421935,20010701,...,,0,0,0,0,0,0,0,0,0

In [2]:

# Gerar planilha para GEPRO/Tadeu
tadeu = final.copy() 
tadeu.rename(columns = {'COMPETENCIA': 'AH_CMPT'}, inplace = True)
competencia = str(input('Qual competência foi auditada (aaaamm)? '))
tadeu.AH_CMPT = competencia
tadeu.to_excel(caminho + "Retorno GEPRO " + competencia + ".xlsx")
print('\n Planilha GEPRO salva!')

# Gerar planilhas para hospitais
hospitais = final.loc[(final['ANALISE'] != 'AIH NÃO ENCONTRADA') &
                      (final['ANALISE'] != 'APROVADA EM OUTRO PROCESSAMENTO') &
                      (final['ANALISE'] != 'LIBERADA')].copy()
hospitais = hospitais.drop(columns=['NOME_PACIENTE', 'IDADE', 'NASCIMENTO', 'NOME_MAE', 'Origem'])
writer = pd.ExcelWriter(caminho + "Retorno hospitais " + competencia + ".xlsx", engine='xlsxwriter')
auditores.to_excel(writer, sheet_name='Auditores')
hospitais.to_excel(writer, sheet_name='Bloqueadas')
writer.close()
print('\n Planilha Hospitais salva!')

# Gerar aba "Bloqueadas"
bloqueadas = final.loc[(final['ANALISE'] != 'LIBERADA') &
                       (final['COMPETENCIA'] != '04/2023') &    #automatizar futuramente
                       (final['Motivo (Preencher com justificativa para o bloqueio / cancelamento)'].notna())
].copy()
print('\n Aba Bloqueadas pronta!')

# Gerar aba "Histórico"
print(historico.COMPETENCIA.value_counts())
filtro = historico['COMPETENCIA']!=(str(input('Qual competência a ser eliminada? ')))
competencias = historico[filtro].copy()
historicoCompleto = pd.concat([competencias, final], ignore_index=True)

# Gerar planilhas para RPM Auditores
#individuais = final[['NUM_AIH', 'PRONTUARIO', 'COMPETENCIA', 'HOSPITAL', 'AUDITOR', 'ANALISE']].copy()
#for auditor in individuais['AUDITOR']:
    

# Agregar abas e gerar planilha final
writer = pd.ExcelWriter(caminho + "Resultado Final Homônimos - Comp 07_23 - Proc 08_23.xlsx", engine='xlsxwriter')
auditores.to_excel(writer, sheet_name='Auditores')
bloqueadas.to_excel(writer, sheet_name='Bloqueadas')
hospitais.to_excel(writer, sheet_name='Hospitais')
historicoCompleto.to_excel(writer, sheet_name='Historico')
writer.close()
print('\n Histórico atualizado!')

Arquivo PDF salvo para o auditor Fatima: RMP_202305_Fatima.pdf
Arquivo PDF salvo para o auditor Guilherme: RMP_202305_Guilherme.pdf
Arquivo PDF salvo para o auditor Julio: RMP_202305_Julio.pdf
Arquivo PDF salvo para o auditor Marcelo: RMP_202305_Marcelo.pdf
Arquivo PDF salvo para o auditor Orlando: RMP_202305_Orlando.pdf
Arquivo PDF salvo para o auditor Simone: RMP_202305_Simone.pdf

In [4]:
pip install dbfread

Collecting dbfreadNote: you may need to restart the kernel to use updated packages.

  Downloading dbfread-2.0.7-py2.py3-none-any.whl (20 kB)
Installing collected packages: dbfread
Successfully installed dbfread-2.0.7

Próximos desafios:
- Automatizar